apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "darbot-memory-mcp.fullname" . }}
  labels:
    {{- include "darbot-memory-mcp.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "darbot-memory-mcp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "darbot-memory-mcp.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "darbot-memory-mcp.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: DARBOT__STORAGE__PROVIDER
              value: {{ .Values.config.storage.provider | quote }}
            {{- if eq .Values.config.storage.provider "FileSystem" }}
            - name: DARBOT__STORAGE__FILESYSTEM__ROOTPATH
              value: {{ .Values.config.storage.fileSystem.rootPath | quote }}
            {{- end }}
            - name: DARBOT__FILENAMETEMPLATE
              value: {{ .Values.config.fileNameTemplate | quote }}
            - name: DARBOT__HASHALGORITHM
              value: {{ .Values.config.hashAlgorithm | quote }}
            - name: DARBOT__CORS__ALLOWEDORIGINS
              value: {{ .Values.config.cors.allowedOrigins | quote }}
            - name: DARBOT__AUTH__MODE
              value: {{ .Values.config.auth.mode | quote }}
            {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- if .Values.healthCheck.enabled }}
          livenessProbe:
            {{- toYaml .Values.healthCheck.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.healthCheck.readinessProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- if and (eq .Values.config.storage.provider "FileSystem") .Values.persistence.enabled }}
            - name: data
              mountPath: /data
            {{- end }}
            {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        {{- if and (eq .Values.config.storage.provider "FileSystem") .Values.persistence.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "darbot-memory-mcp.fullname" . }}
        {{- end }}
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}