apiVersion: v2
name: darbot-memory-mcp
description: A Helm chart for Darbot Memory MCP server
type: application
version: 1.0.0
appVersion: "1.0.0"
home: https://github.com/darbotlabs/darbot-memory-mcp
sources:
  - https://github.com/darbotlabs/darbot-memory-mcp
maintainers:
  - name: Darbot Labs
    email: support@darbotlabs.com
keywords:
  - mcp
  - conversation
  - audit
  - memory